services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - 9010:9000 # Storage
      - 9011:9001 # Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data
    entrypoint: []
    command: minio server /data --address :9000 --console-address :9001
    healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      timeout: 5s
      interval: 5s

  mc:
    image: minio/mc:RELEASE.2023-08-18T21-57-55Z
    depends_on:
      minio:
        condition: service_healthy
    environment:
      S3_BUCKET: app
      S3_REGION: ap-northeast-1
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    entrypoint: []
    command: |
      sh -c "
        mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb myminio/$$S3_BUCKET --region=$$S3_REGION || true
        mc anonymous set download myminio/$$S3_BUCKET
      "

volumes:
  minio:
    driver: local
